/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 hacker-room-new.glb -T
Files: hacker-room-new.glb [34.62MB] > /Users/hsuwinlat/Desktop/jsm pj/threejscc-portfolio/public/models/hacker-room-new-transformed.glb [2.56MB] (93%)
*/

import { useGLTF } from '@react-three/drei';

export function HackerGirl(props) {
  const { nodes, materials } = useGLTF('/models/girl.glb');
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            geometry={nodes.Object_44.geometry}
            material={materials.Material_0}
            skeleton={nodes.Object_44.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_46.geometry}
            material={materials.Material_1}
            skeleton={nodes.Object_46.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_48.geometry}
            material={materials.Material_1}
            skeleton={nodes.Object_48.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_50.geometry}
            material={materials.Material_1}
            skeleton={nodes.Object_50.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_52.geometry}
            material={materials.Material_1}
            skeleton={nodes.Object_52.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/girl.glb');

export default HackerGirl;

