/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 hacker-room-new.glb -T
Files: hacker-room-new.glb [34.62MB] > /Users/hsuwinlat/Desktop/jsm pj/threejscc-portfolio/public/models/hacker-room-new-transformed.glb [2.56MB] (93%)
*/

import { useGLTF } from '@react-three/drei';

export function HackerRoom(props) {
  const { nodes, materials } = useGLTF('/models/bea_hacker.glb');
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            geometry={nodes.Object_91.geometry}
            material={materials.brawl_shader_setup_character_mat}
            skeleton={nodes.Object_91.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_93.geometry}
            material={materials.brawl_shader_setup_character_mat}
            skeleton={nodes.Object_93.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_94.geometry}
            material={materials.character_opac_mat}
            skeleton={nodes.Object_94.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_96.geometry}
            material={materials.brawl_shader_setup_character_mat}
            skeleton={nodes.Object_96.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_98.geometry}
            material={materials.brawl_shader_setup_character_mat}
            skeleton={nodes.Object_98.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_99.geometry}
            material={materials.brawl_shader_setup_character_metal_mat}
            skeleton={nodes.Object_99.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_101.geometry}
            material={materials.bee_hacker_rig_character_flat_mat}
            skeleton={nodes.Object_101.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_102.geometry}
            material={materials.brawl_shader_setup_character_mat}
            skeleton={nodes.Object_102.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_103.geometry}
            material={materials.character_opac_mat}
            skeleton={nodes.Object_103.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_105.geometry}
            material={materials.brawl_shader_setup_character_mat}
            skeleton={nodes.Object_105.skeleton}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes._rootJoint_1} />
          <skinnedMesh
            geometry={nodes.Object_116.geometry}
            material={materials.bee_hacker_rig_character_flat_mat}
            skeleton={nodes.Object_116.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_117.geometry}
            material={materials.bee_hacker_rig_character_metal_mat2}
            skeleton={nodes.Object_117.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_118.geometry}
            material={materials.bee_hacker_rig_character_mat2}
            skeleton={nodes.Object_118.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/bea_hacker.glb');

export default HackerRoom;

